name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - run: php artisan key:generate
    - run: vendor/bin/phpunit
